export const EVENT_NAMES = {
  USER_LOGGED_IN: "USER_LOGGED_IN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  NETWORK_STATUS_CHANGED: "NETWORK_STATUS_CHANGED",
  DATA_FETCH_SUCCESS: "DATA_FETCH_SUCCESS",
  DATA_FETCH_ERROR: "DATA_FETCH_ERROR",
  THEME_CHANGED: "THEME_CHANGED",
  NOTIFICATION_RECEIVED: "NOTIFICATION_RECEIVED",
  BREATHING_CYCLE_END: "BREATHING_CYCLE_END",
  // Add more event names as needed
};
