// ESLint flat config — Expo SDK 53.
// Docs: https://docs.expo.dev/guides/using-eslint/
const expoConfig = require("eslint-config-expo/flat");
const unusedImports = require("eslint-plugin-unused-imports");

module.exports = [
  ...expoConfig,

  // Global ignores (build output + native dirs that are regenerated by prebuild).
  {
    ignores: ["node_modules/", "ios/", "android/", ".expo/", "dist/", "coverage/"],
  },

  {
    files: ["**/*.{ts,tsx,js,jsx}"],
    plugins: {
      "unused-imports": unusedImports,
    },
    rules: {
      // 🚨 Protect React + JSX-referenced component imports from being auto-removed.
      // This project type-checks with `jsx: "react-native"` (from expo/tsconfig.base),
      // which REQUIRES `React` to be in scope for every JSX file — while babel uses the
      // automatic runtime. `jsx-uses-react` marks the `React` import as used in JSX files,
      // and `jsx-uses-vars` marks component imports used only in JSX as used. Without
      // these, the unused-imports autofix below would strip them and break the typecheck.
      "react/jsx-uses-react": "error",
      "react/jsx-uses-vars": "error",

      // unused-imports: auto-remove unused IMPORTS on --fix; only REPORT unused vars
      // (never auto-remove them). `^React$` is belt-and-suspenders; `args:"none"` +
      // `^_` keeps intentional/unused params from being flagged.
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          varsIgnorePattern: "^React$",
          args: "none",
          argsIgnorePattern: "^_",
        },
      ],

      // Defer unused-var detection to the plugin above (avoid duplicate/competing reports).
      "@typescript-eslint/no-unused-vars": "off",
      "no-unused-vars": "off",

      /**
       * OFF for this codebase, deliberately — this is React Native, not the DOM.
       *
       * The rule guards against HTML ambiguity: a bare `'` or `"` in JSX text
       * can be confusing in markup destined for a browser. There is no HTML
       * here; strings render inside <Text>. It accounted for 35 of the 64
       * errors that kept lint out of CI, every one of them an apostrophe in
       * user-facing copy.
       *
       * "Fixing" them would mean rewriting sentences of carefully-worded
       * clinical copy into `&apos;` soup — harder to read and review, easy to
       * typo, and zero safety gained. Turning the rule off is the honest call;
       * leaving 35 permanent errors in the report is what let a REAL crash
       * (a conditionally-called hook in Onboarding) hide among them.
       */
      "react/no-unescaped-entities": "off",
    },
  },

  /**
   * Node scripts. These run under Node, not Metro, so `__dirname`, `require`
   * and friends are legitimately defined — without this they report as
   * `no-undef`, which is a config gap rather than a defect in the script.
   */
  {
    files: ["scripts/**/*.{js,cjs,mjs}", "*.config.js"],
    languageOptions: {
      globals: {
        __dirname: "readonly",
        __filename: "readonly",
        require: "readonly",
        module: "writable",
        process: "readonly",
        console: "readonly",
      },
    },
  },
];
