// source of truth for all keys in Async Storage
export const ASYNC_KEYS_NAME = {
  SW_ZSTORE_PRACTICE_ACTIVITY: "SW_ZSTORE_PRACTICE_ACTIVITY",
  SW_ZSTORE_PRACTICE_SESSION: "SW_ZSTORE_PRACTICE_SESSION",
  SW_ZSTORE_USER: "SW_ZSTORE_USER",
  SW_APP_IS_FIRST_BREATHING_PENDING: "SW_APP_IS_FIRST_BREATHING_PENDING",
  SW_APP_IS_BREATHING_PENDING: "SW_APP_IS_BREATHING_PENDING",
  SW_APP_IS_FIRST_SMOOTHSA_PENDING: "SW_APP_IS_FIRST_SMOOTHSA_PENDING",
};
