// source of truth for all keys in Async Storage
export const ASYNC_KEYS_NAME = {
  SW_ZSTORE_PRACTICE_ACTIVITY: "SW_ZSTORE_PRACTICE_ACTIVITY",
  SW_ZSTORE_PRACTICE_SESSION: "SW_ZSTORE_PRACTICE_SESSION",
  SW_ZSTORE_USER: "SW_ZSTORE_USER",
  SW_APP_IS_FIRST_BREATHING_PENDING: "SW_APP_IS_FIRST_BREATHING_PENDING",
  SW_APP_IS_BREATHING_PENDING: "SW_APP_IS_BREATHING_PENDING",
  SW_APP_IS_FIRST_SMOOTHSA_PENDING: "SW_APP_IS_FIRST_SMOOTHSA_PENDING",
  SW_ZSTORE_MOOD_CHECK: "SW_ZSTORE_MOOD_CHECK_V2",
  SW_ZSTORE_PRACTICE_STATS: "SW_ZSTORE_PRACTICE_STATS",
  SW_ZSTORE_REMINDERS: "SW_ZSTORE_REMINDERS",
  SW_ZSTORE_ONBOARDING: "SW_ZSTORE_ONBOARDING",
  SW_ZSTORE_TRENDS: "SW_ZSTORE_TRENDS",
  SW_ZSTORE_PACKS: "SW_ZSTORE_PACKS",
  SW_ZSTORE_OASES: "SW_ZSTORE_OASES",
  SW_ZSTORE_PROGRESS_REPORT: "SW_ZSTORE_PROGRESS_REPORT",
  SW_ZSTORE_STAMINA_NOTIFICATION: "SW_ZSTORE_STAMINA_NOTIFICATION",
};
