/**
 * @deprecated THIS SCREEN IS OBSOLETE.
 * PLEASE DO NOT EDIT THIS FILE.
 * The dashboard functionality has been moved to Home/index.tsx.
 */
import { StyleSheet, View, Text } from "react-native";
import React, { useCallback, useEffect, useState } from "react";
import { useFocusEffect, useNavigation } from "@react-navigation/native";
import { useUserStore } from "../../stores/user";
import { useSessionStore } from "../../stores/session";
import { useOnboardingStore } from "../../stores/onboarding";
import { useMoodCheckStore } from "../../stores/mood";
import { useEventStore } from "../../stores/events";
import usePullToRefresh from "../../hooks/usePullToRefresh";
import { getUserPreferences } from "../../api/settings/userPreference";
import { getAllPracticeActivitiesBySessionId } from "../../api/practiceActivities";
import { getUserStats } from "../../api/stats";
import {
  getAllSessionsOfUser,
  createSession,
} from "../../api/practiceSessions";
import {
  getLatestUserOnboardingStatus,
  getActiveOnboardingFlow,
} from "../../api/onboarding";
import { startOasesCollection, getOasesProgress } from "../../api/oases";
import { getUserBehaviorHistoricalTrend } from "../../api/userBehaviorTrends";
import { ClinicalDomain } from "../../api/userBehaviorTrends/types";
import { theme } from "../../Theme/tokens";
import { parseTextStyle } from "../../util/functions/parseStyles";
import CustomScrollView from "../../components/CustomScrollView";
import ScreenView from "../../components/ScreenView";
import OnboardingReminderCard from "../../components/OnboardingReminderCard";
import OASESWidget from "../../components/OASESWidget";
import MoodCheck from "./components/MoodCheck";
import ResourceStats from "./components/ResourceStats";
import Progress from "./components/Progress";
import Tiles from "./components/Tiles";
import DailyPractice from "./components/DailyPractice";
import BuyPro from "../Settings/components/BuyPro";
import BottomSheetModal from "../../components/BottomSheetModal";
import BgPattern_404 from "../../assets/sw-bg/BgPattern_404";
import ErrorFace from "../../assets/sw-faces/ErrorFace";
import { EVENT_NAMES } from "../../stores/events/constants";

const Academy = () => {
  useEffect(() => {
    console.warn("Academy Screen is DEPRECATED. Please use Home instead.");
  }, []);

  const navigation = useNavigation<any>();
  const { user, setUser } = useUserStore();
  const { practiceSession, setSession, clearSession } = useSessionStore();
  const { events, clear, emit } = useEventStore();
  const { hasRecordedToday } = useMoodCheckStore();

  // --- SYNC & LOG ONBOARDING STATUS ---
  useEffect(() => {
    if (!user?.id) return;

    const syncStatus = async () => {
      try {
        console.log("\x1b[33m%s\x1b[0m", "--- CHECKING ONBOARDING STATUS ---");

        // 1. Log current local state
        const localStatus = user.hasCompletedOnboarding;
        console.log(
          localStatus ? "\x1b[32m%s\x1b[0m" : "\x1b[31m%s\x1b[0m",
          `[LOCAL] Onboarding Completed: ${localStatus}`,
        );

        // 2. Fetch truth from backend
        const status = await getLatestUserOnboardingStatus(user.id);

        console.log(
          status.hasCompleted ? "\x1b[32m%s\x1b[0m" : "\x1b[31m%s\x1b[0m",
          `[BACKEND] Onboarding Completed: ${status.hasCompleted} (Version: ${status.latestFlowVersion})`,
        );

        // 3. Sync if mismatch
        if (status.hasCompleted !== user.hasCompletedOnboarding) {
          console.log(
            "\x1b[33m%s\x1b[0m",
            ">>> SYNCING LOCAL STORE WITH BACKEND <<<",
          );
          setUser({ ...user, hasCompletedOnboarding: status.hasCompleted });
        }
      } catch (err) {
        console.error("Failed to sync onboarding status:", err);
      }
    };

    syncStatus();
  }, [user?.id, setUser]);

  console.log(
    "Academy Screen - User:",
    user?.id,
    "HasCompletedOnboarding:",
    user?.hasCompletedOnboarding,
  );

  // --- NEW: Local State for Error Modal ---
  const [errorModalVisible, setErrorModalVisible] = useState(false);
  const [errorTitle, setErrorTitle] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  // ----------------------------------------
  const [practiceStats, setPracticeStats] = useState<any>(null); // Added state
  const [oasesProgress, setOasesProgress] = useState<{
    dayNumber: number;
    totalDays: number;
  } | null>(null);

  const currentOnboardingScreen = useOnboardingStore((s) => s.currentScreen);
  const onboardingFlow = useOnboardingStore((s) => s.flow);
  const getTotalScreens = useOnboardingStore((s) => s.getTotalScreens);
  const totalOnboardingScreens = onboardingFlow ? getTotalScreens() : 1;

  const syncSessionWithBackend = useCallback(async () => {
    if (!user) {
      if (practiceSession) {
        clearSession();
      }
      return;
    }
    try {
      const activeSessions = await getAllSessionsOfUser({
        userId: user.id,
        sessionStatus: "ONGOING",
      });
      const backendOngoingSession = activeSessions?.[0];

      if (backendOngoingSession) {
        if (
          practiceSession?.id !== backendOngoingSession.id ||
          practiceSession?.status !== "ONGOING"
        ) {
          setSession(backendOngoingSession);
        }
      } else {
        if (practiceSession && practiceSession.status === "ONGOING") {
          clearSession();
        }
      }
    } catch (error) {
      console.error("Failed to sync session with backend:", error);
    }
  }, [user, practiceSession, setSession, clearSession]);

  const handleScreenRefresh = useCallback(async () => {
    await syncSessionWithBackend();
    if (user?.id) {
      const practiceStats = await getUserStats(user.id);
      setPracticeStats(practiceStats);
    }
  }, [syncSessionWithBackend, user?.id, setPracticeStats]);

  const { refreshControl, refreshing } = usePullToRefresh(handleScreenRefresh);

  useFocusEffect(
    React.useCallback(() => {
      syncSessionWithBackend();
    }, [syncSessionWithBackend]),
  );

  const startNewSession = async () => {
    if (!user) return;
    try {
      const newSessionData = await createSession({ userId: user.id });
      if (newSessionData) {
        setSession(newSessionData);
      }
    } catch (error) {
      console.error("Failed to create new session:", error);
    }
  };

  // --- UPDATED: Listen for Modal Events ---
  useEffect(() => {
    if (!events || events.length === 0) return;

    for (const event of events) {
      if (event.name === EVENT_NAMES.SHOW_ERROR_MODAL) {
        console.log("→ Error modal triggering via Event Store...");

        // 1. Set the content
        setErrorTitle(event.detail.modalTitle || "Something went wrong");
        setErrorMessage(
          event.detail.errorMessage || "An unexpected error occurred.",
        );

        // 2. Open the modal
        setErrorModalVisible(true);

        // 3. Clear the event so it doesn't fire again
        clear(EVENT_NAMES.SHOW_ERROR_MODAL);
      }
    }
  }, [events, clear]);

  useEffect(() => {
    if (!user) return;
    const fetchUserStats = async () => {
      const practiceStats = await getUserStats(user.id);
      setPracticeStats(practiceStats);
    };
    fetchUserStats();
  }, [user, setPracticeStats]);

  useEffect(() => {
    async function fetchUserBehaviorTrends() {
      const trends = await getUserBehaviorHistoricalTrend(
        ClinicalDomain.AVOIDANCE_BEHAVIOR,
      );
      console.log("User behavior trends:", trends);
    }
    fetchUserBehaviorTrends();
  }, []);

  // --- OASES Rapid Collection Auto-Start ---
  useEffect(() => {
    if (!user?.hasCompletedOnboarding) return;

    const initOases = async () => {
      try {
        console.log("[Academy] initOases: Starting collection...");
        // Step 2: Initialize Collection (Idempotent)
        await startOasesCollection();
        console.log("[Academy] initOases: Collection started/verified.");

        // Fetch Progress (SafeCurrent Day)
        const progress = await getOasesProgress();
        console.log("[Academy] initOases: Progress fetched:", progress);
        setOasesProgress({
          dayNumber: progress.dayNumber + 1, // 0-indexed from backend, display 1-indexed
          totalDays: 7, // Fixed 7-day flow
        });
      } catch (err) {
        console.error("[Academy] Failed to init OASES:", err);
      }
    };

    console.log(
      "[Academy] Checking auto-start conditions. User:",
      user?.id,
      "HasCompletedOnboarding:",
      user?.hasCompletedOnboarding,
    );
    initOases();
  }, [user?.hasCompletedOnboarding]);

  return (
    <ScreenView style={styles.screenView}>
      <CustomScrollView
        refreshControl={refreshControl}
        contentContainerStyle={{ paddingBottom: 130 }}
      >
        <View style={styles.innerContainer}>
          {user && !user.hasCompletedOnboarding ? (
            <>
              <OnboardingReminderCard
                currentStep={currentOnboardingScreen - 1}
                totalSteps={totalOnboardingScreens}
                onPress={async () => {
                  try {
                    const state = useOnboardingStore.getState();
                    if (state.flow && state.currentScreen > 1) {
                      emit(EVENT_NAMES.START_ONBOARDING);
                      return;
                    }
                    const flow = await getActiveOnboardingFlow();
                    state.startFresh(flow);
                    emit(EVENT_NAMES.START_ONBOARDING);
                  } catch (err) {
                    console.error("Failed to load onboarding flow:", err);
                  }
                }}
              />
            </>
          ) : (
            <>
              <OASESWidget
                dayNumber={oasesProgress?.dayNumber}
                totalDays={oasesProgress?.totalDays}
                onPress={() => {
                  // Navigate to OASES Intro via DailyPracticeStack
                  // Assuming "DailyPracticeStack" is the route name in AcademyStack
                  // and it can handle nested params or just defaults.
                  // Based on standard React Navigation nesting:
                  navigation.navigate("DailyPracticeStack", {
                    screen: "OASESIntro",
                  });
                }}
              />
            </>
          )}
          {!hasRecordedToday && <MoodCheck />}
          <ResourceStats refreshing={refreshing} />
          <Progress />
          {!refreshing && <DailyPractice onClickStart={startNewSession} />}
          <BuyPro />
          <Tiles />
        </View>
      </CustomScrollView>

      {/* ---  Error Modal Implementation --- */}
      <BottomSheetModal
        visible={errorModalVisible}
        onClose={() => setErrorModalVisible(false)}
        maxHeight="40%" // Adjust height preference
      >
        <BgPattern_404 />
        <View style={styles.modalContent}>
          <Text style={styles.modalTitle}>{errorTitle}</Text>
          <Text style={styles.modalMessage}>{errorMessage}</Text>
          <ErrorFace size={152} />
        </View>
      </BottomSheetModal>
      {/* --------------------------------------- */}
    </ScreenView>
  );
};

export default Academy;

const styles = StyleSheet.create({
  screenView: {
    paddingBottom: 0,
  },
  innerContainer: {
    gap: 32,
    flex: 1,
  },
  // --- New Modal Styles ---
  modalContent: {
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    gap: 16,
  },
  modalTitle: {
    color: theme.colors.text.title,
    ...parseTextStyle(theme.typography.Heading3),
    textAlign: "center",
  },
  modalMessage: {
    color: theme.colors.text.default,
    ...parseTextStyle(theme.typography.Body),
    textAlign: "center",
    lineHeight: 22,
    maxWidth: "80%", // Added for better readability
  },
  closeButton: {
    marginTop: 8,
    backgroundColor: theme.colors.surface.default, // Light gray/neutral
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.border.default,
  },
  closeButtonText: {
    color: theme.colors.text.default,
    ...parseTextStyle(theme.typography.BodySmall),
    fontWeight: "600",
  },
});
